### ISSUE TITLE
Bot stucks on date from the Past in periodic task start date

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/rooms#33]
### Describe the bug

Bot stucks when I try to set date from the past in periodic task and does not respond in any way until you start the dialogue again using the /start command.

### Reproduction

1. Start creating periodic task.
2. Send date from the past.
3. Try to click buttons, or send messages - it will not respond.
4. Send /start command - and it works.

**Comment by Makcal** [comment]
I cannot reproduce the bug. Is there still a problem? @dantetemplar

**Comment by dantetemplar** [comment]
> I cannot reproduce the bug. Is there still a problem? @dantetemplar

I guess there is no problem now.
