### ISSUE TITLE
Delete orders

### ISSUE THREAD

**Issue by Makcal** [one-zero-eight/rooms#36]
There is no possibility to remove orders now

**Comment by dantetemplar** [comment]
@Makcal There is same problem for Rules

**Comment by Makcal** [comment]
> @Makcal There is same problem for Rules

Resolved!

**Comment by Makcal** [comment]
This feature is redundant since an order is now managed in the bot like an entity exclusively owned by the task ([issue](https://github.com/one-zero-eight/rooms-bot/issues/22)).
